//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accounts()
        {
            this.SessionsAccounts = new HashSet<SessionsAccounts>();
        }
    
        public int idAccount { get; set; }
        public int idStatus { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> DateRegistration { get; set; }
    
        public virtual StatusAccounts StatusAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionsAccounts> SessionsAccounts { get; set; }
        public virtual Users Users { get; set; }
    }
}
