//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ServiceModel;

    public partial class accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accounts()
        {
            this.SessionsAccounts = new HashSet<SessionsAccounts>();
        }


        public accounts(int IdAccont)
        {
            this.idAccount = IdAccont;
        }


        // Конструктор для инициализации данных аккаунта и пользователя
        public accounts
            (
            int idStatus,
            string login,
            string password,
            Nullable<System.DateTime> DateRegistration,
            string Name,
            string Family,
            string Surname,
            string Gender,
            int StatusUser,
            string NumberPhone,
            DateTime? DateOfBirthday)
        {
            this.idStatus = idStatus;
            this.login = login;
            this.password = password;
            this.DateRegistration = DateRegistration;
            this.Users = new Users(idAccount, StatusUser, Name, Family, Surname, Gender, NumberPhone, DateOfBirthday);            
        }

        // Переопределяем конструктор, если требуется добавить айди аккаунта к инициализации объекта
        public accounts
            (
            int idStatus,
            string login,
            string password,
            Nullable<System.DateTime> DateRegistration,
            string Name,
            string Family,
            string Surname,
            string Gender,
            int StatusUser,
            string NumberPhone,
            DateTime? DateOfBirthday,
            int idAccount)
            :this (idAccount)
        {
            this.idStatus = idStatus;
            this.login = login;
            this.password = password;
            this.DateRegistration = DateRegistration;
            this.Users = new Users(idAccount, StatusUser, Name, Family, Surname, Gender, NumberPhone, DateOfBirthday);
        }


        #region Свойства аккаунта

        public int idAccount { get; set; }
        public int idStatus { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> DateRegistration { get; set; }


        public OperationContext operationContext { get; set; } // Для работы сервера с юзерами со стороны клиента

        public virtual StatusAccounts StatusAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionsAccounts> SessionsAccounts { get; set; }
        public virtual Users Users { get; set; }

        #endregion
    }
}
