//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int idAttendance { get; set; }
        public int IdLesson { get; set; }
        public int StudentId { get; set; }
        public string Mark { get; set; }
    
        public Attendance()
        {

        }

        public Attendance(int IdLesson, int StudentId)
        {
            this.IdLesson = IdLesson;
            this.StudentId = StudentId;
        }

        public virtual LessonsDate LessonsDate { get; set; }
        public virtual Marks Marks { get; set; }
        public virtual StudentsGroup StudentsGroup { get; set; }
    }
}
