//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int idAttendance { get; set; }
        public int IdTeacher { get; set; }
        public int IdGroup { get; set; }
        public int IdDiscipline { get; set; }
        public Nullable<int> NumberSemester { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> DateLesson { get; set; }
        public Nullable<int> LessonNumber { get; set; }
        public string Mark { get; set; }
    
        public virtual LessonsDate LessonsDate { get; set; }
        public virtual StudentsGroup StudentsGroup { get; set; }
        public virtual TeacherDisciplines TeacherDisciplines { get; set; }
    }
}
