//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {


        public Attendance()
        {

        }

        // Конструктор
        public Attendance(int idAttendance, int IdLesson, int StudentId, string Mark)
        {
            this.idAttendance = idAttendance;
            this.IdLesson = IdLesson;
            this.StudentId = StudentId;
            this.Mark = Mark;
        }

        #region Свойства

        public int idAttendance { get; set; }
        public int IdLesson { get; set; }
        public int StudentId { get; set; }
        public string Mark { get; set; }
    
        public virtual LessonsDate LessonsDate { get; set; }
        public virtual Marks Marks { get; set; }
        public virtual StudentsGroup StudentsGroup { get; set; }

        #endregion
    }
}
