//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDisciplines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupDisciplines()
        {
            this.FinalAttendances = new HashSet<FinalAttendances>();
            this.LessonsDate = new HashSet<LessonsDate>();
        }
    
        public GroupDisciplines(int IdTeacherDiscipline, int IdGroup, int NumberSemester)
        {
            this.IdTeacherDiscipline = IdTeacherDiscipline;
            this.IdGroup = IdGroup;
            this.NumberSemester = NumberSemester;
        }

        public int idTeacherActivities { get; set; }
        public int IdTeacherDiscipline { get; set; }
        public int IdGroup { get; set; }
        public int NumberSemester { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalAttendances> FinalAttendances { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual TeacherDisciplines TeacherDisciplines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonsDate> LessonsDate { get; set; }
    }
}
