//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {


        public Images()
        {

        }

        public Images(int IdNews, byte[] Image, string format_img)
        {
            this.IdNews = IdNews;
            this.Image = Image;
            this.format_img = format_img;
        }

        #region Свойства

        public int IdImage { get; set; }
        public int IdNews { get; set; }
        public byte[] Image { get; set; }
        public string format_img { get; set; }
    
        public virtual News News { get; set; }

        #endregion
    }
}
