//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderArchive
    {
        public int IdOrder { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Commentary { get; set; }
        public int IdOrderType { get; set; }

        public OrderArchive()
        {

        }

        public OrderArchive(string Commentary, int IdOrderType)
        {
            this.Commentary = Commentary;
            this.IdOrderType = IdOrderType;
            this.Date = DateTime.Now;
        }


        public virtual OrderTypes OrderTypes { get; set; }
    }
}
