//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionsAccounts
    {

        #region Свойства

        public int idSession { get; set; }
        public int idAccount { get; set; }
        public Nullable<System.DateTime> StartLogin { get; set; }
        public Nullable<System.DateTime> EndLogin { get; set; }
    
        public virtual accounts accounts { get; set; }

        #endregion
    }
}
