//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentsGroup()
        {
            this.Attendance = new HashSet<Attendance>();
            this.FinalAttendances = new HashSet<FinalAttendances>();
        }


        public StudentsGroup(int IdStudent, int idGroup, int NumberInJournal)
        {
            this.IdStudent = IdStudent;
            this.idGroup = idGroup;
            this.NumberInJournal = NumberInJournal;
        }

        public int IdStudent { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> NumberInJournal { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalAttendances> FinalAttendances { get; set; }
    }
}
