//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.TeacherDisciplines = new HashSet<TeacherDisciplines>();
        }


        // Конструктор для инициализации данных
        public Users(int idUser, int idUserStatus, string Name, string Family, string Surname, string Gender, string NumberPhone, DateTime? DateOfBirthdays)
        {
            this.idUser = idUser;
            this.idUserStatus = idUserStatus;
            this.Name = Name;
            this.Family = Family;
            this.Surname = Surname;
            this.Gender = Gender;
            this.NumberPhone = NumberPhone;

            if (DateOfBirthdays.HasValue)
                this.DateOfBirthDay = new DateTime(DateOfBirthdays.Value.Year, DateOfBirthdays.Value.Month, DateOfBirthdays.Value.Day);
        }


        #region Свойства юзера

        public int idUser { get; set; }
        public int idUserStatus { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string NumberPhone { get; set; }
        public Nullable<System.DateTime> DateOfBirthDay { get; set; }

        public virtual accounts accounts { get; set; }
        public virtual StudentsGroup StudentsGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherDisciplines> TeacherDisciplines { get; set; }
        public virtual UserStatus UserStatus { get; set; }

        #endregion
    }
}
