//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProgramJournal_DB.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.ITransferService")]
    public interface ITransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferService/GetAccounts", ReplyAction="http://tempuri.org/ITransferService/GetAccountsResponse")]
        MyModelLibrary.accounts GetAccounts(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferService/GetAccounts", ReplyAction="http://tempuri.org/ITransferService/GetAccountsResponse")]
        System.Threading.Tasks.Task<MyModelLibrary.accounts> GetAccountsAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransferService/DisconnectUser")]
        void DisconnectUser(int IdAccount);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransferService/DisconnectUser")]
        System.Threading.Tasks.Task DisconnectUserAsync(int IdAccount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransferServiceChannel : MyProgramJournal_DB.MyService.ITransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferServiceClient : System.ServiceModel.ClientBase<MyProgramJournal_DB.MyService.ITransferService>, MyProgramJournal_DB.MyService.ITransferService {
        
        public TransferServiceClient() {
        }
        
        public TransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyModelLibrary.accounts GetAccounts(string login, string password) {
            return base.Channel.GetAccounts(login, password);
        }
        
        public System.Threading.Tasks.Task<MyModelLibrary.accounts> GetAccountsAsync(string login, string password) {
            return base.Channel.GetAccountsAsync(login, password);
        }
        
        public void DisconnectUser(int IdAccount) {
            base.Channel.DisconnectUser(IdAccount);
        }
        
        public System.Threading.Tasks.Task DisconnectUserAsync(int IdAccount) {
            return base.Channel.DisconnectUserAsync(IdAccount);
        }
    }
}
